name: Sync Dev

on:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
        fetch-depth: 0
    
    - run: |
        git merge main
        git push
