name: Dev Docs

on:
  workflow_dispatch:
  push:
    branches: [ dev ]

env:
  POETRY_VERSION: "1.3.2"
  PYTHON_VERSION: "3.10"
  CHANGELOG_URL: "https://raw.githubusercontent.com/0xPlaygrounds/subgrounds/main/CHANGELOG.md"
  CONTRIBUTING_URL: "https://raw.githubusercontent.com/0xPlaygrounds/subgrounds/main/CONTRIBUTING.md"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # ---------------------------------------------
    # -----           gather repo             -----
    # ---------------------------------------------
    - uses: actions/checkout@v3

    # ---------------------------------------------
    # -----      setup and cache python       -----
    # ---------------------------------------------
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache poetry
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-${{ env.POETRY_VERSION }}

    - name: Install poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
        virtualenvs-in-project: true

    - name: Cache venv
      id: cache-venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}-

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: poetry install --no-root

    #----------------------------------------------
    #  -----       build & deploy docs       -----
    #----------------------------------------------
    - name: Grab subgrounds changelog and contributing
      run: |
        curl $CHANGELOG_URL > docs/subgrounds/changelog.md
        curl $CONTRIBUTING_URL > docs/subgrounds/contributing.md
        cp CONTRIBUTING.md docs/meta/contributing.md


    - name: Build and deploy documentation
      if: github.repository == '0xPlaygrounds/docs'
      run: |
        set -e
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        git worktree add --detach dev-build
        poetry run mudkip build
        cd dev-build
        git fetch
        git checkout dev-build
        mv -v ../docs/_build/dist/* .
        git add .
        git commit -m 'Update Dev Docs'
        git push -f
        cd ..
        git worktree remove dev-build
