name: Graph Docs

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "src/**"
      - "poetry.lock"
      - "pyproject.toml"

env:
  POETRY_VERSION: "1.3.2"
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # ---------------------------------------------
    # -----           gather repo             -----
    # ---------------------------------------------
    - uses: actions/checkout@v3

    # ---------------------------------------------
    # -----      setup and cache python       -----
    # ---------------------------------------------
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache poetry
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-${{ env.POETRY_VERSION }}

    - name: Install poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
        virtualenvs-in-project: true

    - name: Cache venv
      id: cache-venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}-

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: poetry install --no-root

    #----------------------------------------------
    #  -----       build & deploy docs       -----
    #----------------------------------------------

    - name: Checkout 'graph-docs'
      uses: actions/checkout@v3
      with:
          path: 'graph_docs'
          ref: 'graph-docs'
          fetch-depth: 0

    - name: Build graph-docs
      if: github.repository == '0xPlaygrounds/docs'
      run: |
        python src/main.py
        cp -r graph_docs_output/ graph_docs/
        SHORT_HASH=$(git rev-parse --short HEAD)
        cd graph_docs
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "🤖 Generated from $SHORT_HASH"
        git push
