name: Graph Docs

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "src/**"
      - "poetry.lock"
      - "pyproject.toml"
      - .github/workflows/graph-docs.yml

env:
  POETRY_VERSION: "1.3.2"
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # ---------------------------------------------
    # -----           gather repo             -----
    # ---------------------------------------------
    - uses: actions/checkout@v3

    # ---------------------------------------------
    # -----      setup and cache python       -----
    # ---------------------------------------------
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: pip install subgrounds mistune

    #----------------------------------------------
    #  -----       build & deploy docs       -----
    #----------------------------------------------

    - name: Checkout 'graph-docs'
      uses: actions/checkout@v3
      with:
          path: 'graph_docs'
          ref: 'graph-docs'
          fetch-depth: 0

    - name: Build graph-docs
      if: github.repository == '0xPlaygrounds/docs'
      run: |
        rm -rf graph_docs/docs
        mkdir -pv graph_docs/docs
        python src/main.py
        cp -r graph_docs_output/* graph_docs/docs
        SHORT_HASH=$(git rev-parse --short HEAD)
        cd graph_docs
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "🤖 Generated from $SHORT_HASH"
        git push
